FROM ubuntu:16.04
MAINTAINER Matt Bentley <mbentley@mbentley.net>

ARG DOCKER_EE_URL

RUN apt-get update &&\
  apt-get install -y apt-transport-https ca-certificates curl &&\
  curl -fsSL "${DOCKER_EE_URL}"/gpg | apt-key add - &&\
  echo "deb [arch=amd64] ${DOCKER_EE_URL} xenial stable-17.06" > /etc/apt/sources.list.d/docker.list &&\
  apt-get update &&\
  apt-get install -y docker-ee &&\
  rm -rf /var/lib/apt/lists/* /etc/apt/sources.list.d/docker.list

COPY entrypoint.sh /entrypoint.sh

VOLUME ["/var/lib/docker"]
ENTRYPOINT ["/entrypoint.sh"]
CMD ["dockerd","-s","overlay2","-H","unix:///var/run/docker.sock","-H","0.0.0.0:12375"]
