FROM mbentley/docker-in-docker:ce-systemd
MAINTAINER Matt Bentley <mbentley@mbentley.net>

RUN apt-get update &&\
  DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server &&\
  rm -rf /var/lib/apt/lists/* &&\
  rm -v /etc/ssh/ssh_host_*
