#!/bin/bash

# docker dind plugin
# see https://github.com/mbentley/docker-in-docker#docker-dind-plugin for usage

case $1:$2 in
  docker-cli-plugin-metadata:*)
    # return the appropriate metadata when requested
    echo '{"SchemaVersion": "0.1.0","Vendor":"mbentley","Version":"v0.0.1","ShortDescription":"Docker-in-Docker Docker Enterprise"}'
    exit 0
    ;;
  *:*)
    # for all commands, execute the dind_docker_enterprise script
    # shift the parameters to match what dind_docker_enterprise is expecting
    shift

    # export the SCRIPT_PATH variable to override the command
    export SCRIPT_PATH="docker dind"

    # execute the dind script and pass all parameters
    "$(dirname "$(readlink "${0}")")"/scripts/dind_docker_enterprise "${@}"

    # pass the exit code from the dind_docker_enterprise script
    exit $?
    ;;
esac
