#!/bin/bash

set -e

# unset DOCKER_HOST to ensure we are not talking to a machine we shouldn't be
unset DOCKER_HOST

initialize() {
  # set default values; allow for override
  DIND_TAG="${DIND_TAG:-ee-17.03}"
  UCP_REPO="${UCP_REPO:-docker/ucp}"
  UCP_VERSION="${UCP_VERSION:-2.1.4}"
  UCP_IMAGES="${UCP_IMAGES:-${HOME}/ddc/ucp_images_"${UCP_VERSION}".tar.gz}"
  UCP_OPTIONS="${UCP_OPTIONS:-}"
  DTR_REPO="${DTR_REPO:-docker/dtr}"
  DTR_VERSION="${DTR_VERSION:-2.2.5}"
  DTR_IMAGES="${DTR_IMAGES:-${HOME}/ddc/dtr-"${DTR_VERSION}".tar.gz}"
  DDC_LICENSE="${DDC_LICENSE:-${HOME}/Downloads/docker_subscription.lic}"
  DIND_SUBNET="${DIND_SUBNET:-172.19.0.0/16}"
  DIND_DNS="${DIND_DNS:-8.8.8.8}"
  ALIAS_IP="${ALIAS_IP:-10.1.2.3}"

  # check to see what OS and set network interface
  if [ "$(uname -s)" = "Darwin" ]
  then
     NET_IF="${NET_IF:-en0}"
  else
     NET_IF="${NET_IF:-eth0}"
  fi
}

output_info() {
  echo -e "DIND_TAG\t${DIND_TAG}"
  echo -e "UCP_REPO:\t${UCP_REPO}"
  echo -e "UCP_VERSION:\t${UCP_VERSION}"
  echo -e "UCP_IMAGES:\t${UCP_IMAGES}"
  echo -e "UCP_OPTIONS:\t${UCP_OPTIONS}"
  echo -e "DTR_REPO:\t${DTR_REPO}"
  echo -e "DTR_VERSION:\t${DTR_VERSION}"
  echo -e "DTR_IMAGES:\t${DTR_IMAGES}"
  echo -e "DDC_LICENSE:\t${DDC_LICENSE}"
  echo -e "DIND_SUBNET:\t${DIND_SUBNET}"
  echo -e "DIND_DNS:\t${DIND_DNS}"
  echo -e "NET_IF:\t\t${NET_IF}"
  echo -e "ALIAS_IP:\t${ALIAS_IP}"
  exit 0
}

create_net_alias() {
  # run this only on a mac
  if [ "$(uname -s)" = "Darwin" ]
  then
    # check to see if the default ALIAS_IP is set
    if [ "${ALIAS_IP}" = "10.1.2.3" ]
    then
      # check to see if the alias IP is already set
      if ! ifconfig "${NET_IF}" | grep "${ALIAS_IP}" > /dev/null 2>&1
      then
        # create it
        echo "Creating IP alias (requires sudo)..."
        sudo ifconfig "${NET_IF}" alias "${ALIAS_IP}" 255.255.255.0
        echo -e "done.\n"
      else
        # skip creation; already exists
        echo "IP alias (${ALIAS_IP}) already exists"
        echo -e "done.\n"
      fi
    else
      # skip because custom address provided
      echo "Skipping creation of network IP alias; custom address provided"
      echo -e "done.\n"
    fi
  else
    echo "Skipping creation of network IP alias; you're not on a Mac"

    # check to see if the default ALIAS_IP is set
    if [ "${ALIAS_IP}" = "10.1.2.3" ]
    then
      echo "ERROR: ALIAS_IP is not set; set to your host's IP address or installations will fail"
      exit 1
    fi
    echo -e "done.\n"
  fi
}

remove_net_alias() {
  # run this only on a mac
  if [ "$(uname -s)" = "Darwin" ]
  then
    # check to see if the default ALIAS_IP is set
    if [ "${ALIAS_IP}" = "10.1.2.3" ]
    then
      # check to see if the alias IP is already set
      if ifconfig "${NET_IF}" | grep "${ALIAS_IP}" > /dev/null 2>&1
      then
        # remove it
        echo "Removing IP alias (requires sudo)..."
        sudo ifconfig "${NET_IF}" -alias "${ALIAS_IP}" 255.255.255.0
        echo -e "done.\n"
      else
        # skip creation; already exists
        echo "IP alias (${ALIAS_IP}) does not exists; skipping removal"
        echo -e "done.\n"
      fi
    else
      # skip because custom address provided
      echo "Skipping removal of network IP alias; custom address provided"
      echo -e "done.\n"
    fi
  else
    echo "Skipping removal of network IP alias; you're not on a Mac"
    echo -e "done.\n"
  fi
}

create_all() {
  create_net_alias
  create_swarm
  install_ucp
  install_dtr
}

create_swarm() {
  launch_engines
  init_swarm
}

launch_engines() {
  # create dind network
  echo "Checking for subnet availability..."
  check_subnet
  echo -e "done.\n"

  echo "Creating 'dind' network with the subnet ${DIND_SUBNET}..."
  docker -H unix:///var/run/docker.sock network create -d bridge --subnet="${DIND_SUBNET}" dind
  echo -e "done.\n"

  # get subnet prefix
  DIND_SUBNET_PREFIX="$(docker -H unix:///var/run/docker.sock network inspect --format '{{range .IPAM.Config}}{{.Subnet}}{{end}}' dind | awk -F '/' '{print $1}' | awk -F '.' '{print $1"."$2"."$3"."}')"

  echo "Launching docker engines (docker1, docker2, docker3)..."
  # launch docker1
  ENGINE_NUM="1"
  docker -H unix:///var/run/docker.sock run -d \
    -p 127.0.0.1:100${ENGINE_NUM}:12375 \
    -p 4443:4443 \
    --name docker${ENGINE_NUM} \
    --hostname docker${ENGINE_NUM} \
    --privileged \
    --net dind \
    --ip "${DIND_SUBNET_PREFIX}"$((ENGINE_NUM+1)) \
    -v /lib/modules:/lib/modules:ro \
    -v docker${ENGINE_NUM}:/var/lib/docker \
    mbentley/docker-in-docker:"${DIND_TAG}" \
    dockerd -s overlay2 -H unix:///var/run/docker.sock -H tcp://0.0.0.0:12375 --dns "${DIND_DNS}"

  # launch docker2
  ENGINE_NUM="2"
  docker -H unix:///var/run/docker.sock run -d \
    -p 127.0.0.1:100${ENGINE_NUM}:12375 \
    -p 80:80 \
    -p 443:443 \
    --name docker${ENGINE_NUM} \
    --hostname docker${ENGINE_NUM} \
    --privileged \
    --net dind \
    --ip "${DIND_SUBNET_PREFIX}"$((ENGINE_NUM+1)) \
    -v /lib/modules:/lib/modules:ro \
    -v docker${ENGINE_NUM}:/var/lib/docker \
    mbentley/docker-in-docker:"${DIND_TAG}" \
    dockerd -s overlay2 -H unix:///var/run/docker.sock -H tcp://0.0.0.0:12375 --dns "${DIND_DNS}"

  # launch docker3
  ENGINE_NUM="3"
  docker -H unix:///var/run/docker.sock run -d \
    -p 127.0.0.1:100${ENGINE_NUM}:12375 \
    --name docker${ENGINE_NUM} \
    --hostname docker${ENGINE_NUM} \
    --privileged \
    --net dind \
    --ip "${DIND_SUBNET_PREFIX}"$((ENGINE_NUM+1)) \
    -v /lib/modules:/lib/modules:ro \
    -v docker${ENGINE_NUM}:/var/lib/docker \
    mbentley/docker-in-docker:"${DIND_TAG}" \
    dockerd -s overlay2 -H unix:///var/run/docker.sock -H tcp://0.0.0.0:12375 --dns "${DIND_DNS}"
  echo -e "done.\n"
}

start_engines() {
  echo "Starting docker engines (docker1, docker2, docker3)..."
  docker -H unix:///var/run/docker.sock start docker{1..3} || true
  echo -e "done.\n"
}
stop_engines() {
  echo "Stopping docker engines (docker1, docker2, docker3); this may take up to 30 seconds..."
  docker -H unix:///var/run/docker.sock stop -t 30 docker{1..3} || true
  echo -e "done.\n"
}

recycle_engines() {
  stop_engines

  echo "Removing docker engines (docker1, docker2, docker3)..."
  docker -H unix:///var/run/docker.sock rm docker{1..3} || true
  echo -e "done.\n"

  echo "Removing 'dind' network..."
  docker -H unix:///var/run/docker.sock network rm dind || true
  echo -e "done.\n"

  launch_engines
}

init_swarm() {
  echo "Initializing Swarm on docker1..."
  docker -H tcp://127.0.0.1:1001 swarm init
  echo -e "done.\n"

  # get swarm worker join token
  TOKEN=$(docker -H tcp://127.0.0.1:1001 swarm join-token worker -q)

  JOIN_COMMAND="swarm join --token ${TOKEN} $(docker -H unix:///var/run/docker.sock container inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' docker1):2377"

  echo "Joining docker2 to the Swarm..."
  #shellcheck disable=SC2086
  docker -H tcp://127.0.0.1:1002 ${JOIN_COMMAND}
  echo -e "done.\n"

  echo "Joining docker3 to the Swarm..."
  #shellcheck disable=SC2086
  docker -H tcp://127.0.0.1:1003 ${JOIN_COMMAND}
  echo -e "done.\n"
}

connect_engine() {
  ENGINE_NUM="${1}"
  echo "# to connect to a given engine, use:"
  #shellcheck disable=SC2016
  echo '# eval "$(./dind_swarm connect_engine '"${1}"')"'
  echo "export DOCKER_HOST=tcp://127.0.0.1:100${ENGINE_NUM}"
}

install_ucp() {
  create_net_alias
  DOCKER1_IP="$(docker -H unix:///var/run/docker.sock container inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' docker1)"

  # load all UCP images to docker1
  echo "Loading UCP images on docker1..."
  docker -H tcp://127.0.0.1:1001 load -i "${UCP_IMAGES}"
  echo -e "done.\n"

  # load docker/ucp-agent from docker1 to docker2 and docker3
  for i in 2 3
  do
    echo "Loading ${UCP_REPO}-agent:${UCP_VERSION} on docker ${i}..."
    docker -H tcp://127.0.0.1:1001 save "${UCP_REPO}"-agent:"${UCP_VERSION}" | docker -H tcp://127.0.0.1:100${i} load
    echo -e "done.\n"
  done

  echo "Installing UCP on docker1 using controller port 4443..."
  #shellcheck disable=SC2086
  docker -H tcp://127.0.0.1:1001 run -it --rm --name ucp -v /var/run/docker.sock:/var/run/docker.sock "${UCP_REPO}":"${UCP_VERSION}" install ${UCP_OPTIONS} --admin-username admin --admin-password docker123 --host-address "${DOCKER1_IP}" --controller-port 4443 --san "${DOCKER1_IP}" --san "${ALIAS_IP}" --san "$(hostname)" --san "$(hostname -f)" --license "$(cat ${DDC_LICENSE})"

  echo -e "\nUCP should now be available at https://${ALIAS_IP}:4443/"
  echo -e "  Username: admin\tPassword: docker123"
  echo -e "done.\n"
}

install_dtr() {
  echo "Loading DTR images on docker2..."
  docker -H tcp://127.0.0.1:1002 load -i "${DTR_IMAGES}"
  echo -e "done.\n"

  echo "Installing DTR on docker2 using DTR replica ports 80 and 443..."
  docker -H tcp://127.0.0.1:1002 run -it --rm "${DTR_REPO}":"${DTR_VERSION}" install --ucp-url https://"${ALIAS_IP}:4443" --ucp-username admin --ucp-password docker123 --ucp-node docker2 --ucp-ca "$(curl -ks https://"${ALIAS_IP}":4443/ca)" --dtr-external-url "${ALIAS_IP}"

  echo -e "\nDTR should now be available at https://${ALIAS_IP}/"
  echo -e "  Username: admin\tPassword: docker123"
  echo -e "done.\n"
}

destroy_swarm() {
  sudo bash -c 'echo -n'
  echo "Removing docker engines (docker1, docker2, docker3)..."
  docker -H unix:///var/run/docker.sock kill docker1 docker2 docker3 || true
  docker -H unix:///var/run/docker.sock rm docker1 docker2 docker3 || true
  echo -e "done.\n"

  echo "Removing persistent data for docker engines (docker1, docker2, docker3)..."
  docker -H unix:///var/run/docker.sock volume rm docker1 docker2 docker3 || true
  echo -e "done.\n"

  echo "Removing 'dind' network..."
  docker -H unix:///var/run/docker.sock network rm dind || true
  echo -e "done.\n"

  remove_net_alias
}

check_subnet() {
  for i in $(docker -H unix:///var/run/docker.sock network ls -q)
  do
    if [ "$(docker -H unix:///var/run/docker.sock network inspect --format '{{range .IPAM.Config}}{{.Subnet}}{{end}}' "${i}")" = "${DIND_SUBNET}" ]
    then
      echo "ERROR: the subnet specified (${DIND_SUBNET}) for the 'dind' network conflicts with the existing network '$(docker -H unix:///var/run/docker.sock network inspect --format '{{.Name}}' "${i}")'"
      echo "Use DIND_SUBNET to specify a different subnet when launching a new environment"
      exit 1
    fi
  done

  echo "Subnet (${DIND_SUBNET}) is available."
}

main() {
  initialize

  case ${1} in
    create_all|create_swarm|start_engines|stop_engines|recycle_engines|create_net_alias|remove_net_alias|install_ucp|install_dtr|destroy_swarm|output_info)
      ${1}
      ;;
    connect_engine)
      if [ -z "${2}" ]
      then
        echo "Error: Missing engine name"
        echo "Usage: $0 connect_engine docker1"
      else
        ${1} "${2}"
      fi
      ;;
    *)
      echo "Basic Usage:"
      echo -e "  $0 {create_all|create_swarm|install_ucp|install_dtr|destroy_swarm|output_info}"
      echo -e "\nAdditional utility usage:"
      echo -e "  $0 {connect_engine|start_engines|stop_engines|recycle_engines|create_net_alias|remove_net_alias}"
      echo -e "\nCurrent set environment variables:"
      output_info
      ;;
  esac
}

main "${@}"
